language: go
go:
  - "1.11"

notifications:
  email: false

env:
  - GO111MODULE=on

before_install:
  - make download-tools

install:
  - make install

script:
  - make generate
  - make lint
  - make test
  - go build -o build/executable

after_success:
  - bash <(curl -s https://codecov.io/bash)