services:
  - docker

sudo: required

language: go
go:
  - "1.12"

notifications:
  email: false

env:
  global:
    - UPX_VERSION="3.95"
    - GO111MODULE=on

before_install:
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
  - curl -fSL https://github.com/upx/upx/releases/download/v${UPX_VERSION}/upx-${UPX_VERSION}-amd64_linux.tar.xz -o ~/upx.tar.xz && tar -xf ~/upx.tar.xz -C ~ && mv ~/upx-${UPX_VERSION}-amd64_linux/upx ~/bin
  - nvm install 11.11.0
  - make download-tools

install:
  - make install

script:
  - make generate
  - make lint
  - make test
  - make build-js

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      if [[ $TRAVIS_TAG != "v"* ]]; then exit 1; fi;
      make build-bin fix-build-owner build-compress package-zip docker-build;
    fi

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/*.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: make docker-login-ci docker-push docker-push-manifest
    skip_cleanup: true
    on:
      tags: true
